/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mypackage;
import javax.swing.*;  
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import static mypackage.QueriesForm.password;
import static mypackage.QueriesForm.url;
import static mypackage.QueriesForm.username;
/**
 *
 * @author maria
 */
public class firstForm extends javax.swing.JFrame {
    int numOfOrder;
    String viewName;
    String selected;
    String selected2;
    DefaultListModel dm=new DefaultListModel();
    DefaultListModel dm2=new DefaultListModel();
    static String driverClassName="org.postgresql.Driver";
    static String url="jdbc:postgresql://dblabs.iee.ihu.gr:5432/it174865";
    static Connection dbConnection=null;
    static String username="it174865";
    static String password="Aa194523511378";
    static Statement statement=null;

    /**
     * Creates new form firstForm
     */
    public firstForm() {
        initComponents();
    }
    public java.sql.Connection connect() throws SQLException {
        return DriverManager.getConnection(url, username, password);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        appetizerB = new javax.swing.JButton();
        meatB = new javax.swing.JButton();
        saladsB = new javax.swing.JButton();
        fishB = new javax.swing.JButton();
        beersB = new javax.swing.JButton();
        soft_drinksB = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        theList = new javax.swing.JList<>();
        removeB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        theList2 = new javax.swing.JList<>();
        submitB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        newOrderB = new javax.swing.JButton();
        controlB = new javax.swing.JButton();
        queriesB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(905, 550));

        appetizerB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/french-fries_10.png"))); // NOI18N
        appetizerB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appetizerBActionPerformed(evt);
            }
        });

        meatB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/burger_10.png"))); // NOI18N
        meatB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meatBActionPerformed(evt);
            }
        });

        saladsB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/salad_10.png"))); // NOI18N
        saladsB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saladsBActionPerformed(evt);
            }
        });

        fishB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/fish_10.png"))); // NOI18N
        fishB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fishBActionPerformed(evt);
            }
        });

        beersB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/beer_10.png"))); // NOI18N
        beersB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beersBActionPerformed(evt);
            }
        });

        soft_drinksB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/cola_10.png"))); // NOI18N
        soft_drinksB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soft_drinksBActionPerformed(evt);
            }
        });

        theList.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                theListAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        theList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                theListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(theList);

        removeB.setText("REMOVE SELECTED FROM LIST");
        removeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(theList2);

        submitB.setText("SUBMIT");
        submitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBActionPerformed(evt);
            }
        });

        jLabel1.setText("Select products from the list");

        jLabel2.setText("Select from menu");

        jLabel3.setText("These products are for new order if you");

        newOrderB.setText("NEW ORDER");
        newOrderB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newOrderBActionPerformed(evt);
            }
        });

        controlB.setText("CONTROL DATA");
        controlB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controlBActionPerformed(evt);
            }
        });

        queriesB.setText("QUERIES FORM");
        queriesB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queriesBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(appetizerB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(beersB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(meatB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fishB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saladsB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(soft_drinksB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1)
                    .addComponent(removeB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(newOrderB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitB)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(controlB, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(queriesB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(controlB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saladsB, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(appetizerB, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(queriesB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(removeB, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(newOrderB, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fishB, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(meatB, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(soft_drinksB, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(beersB, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void appetizerBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appetizerBActionPerformed
        try {
            String appetizer="appetizer";
            meth(appetizer);
        } catch (Exception ex) {
            Logger.getLogger(firstForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_appetizerBActionPerformed

    private void soft_drinksBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soft_drinksBActionPerformed
        try {
            String soft_drinks="soft_drinks";
            meth(soft_drinks);
        } catch (Exception ex) {
            Logger.getLogger(firstForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_soft_drinksBActionPerformed

    private void saladsBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saladsBActionPerformed
        try {
            String salads="salads";
            meth(salads);
        } catch (Exception ex) {
            Logger.getLogger(firstForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_saladsBActionPerformed

    private void theListAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_theListAncestorAdded
        
    }//GEN-LAST:event_theListAncestorAdded

    private void beersBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beersBActionPerformed
         try {
            String beers="beers";
            meth(beers);
        } catch (Exception ex) {
            Logger.getLogger(firstForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_beersBActionPerformed

    private void meatBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meatBActionPerformed
        try {
            String meat="meat";
            meth(meat);
        } catch (Exception ex) {
            Logger.getLogger(firstForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_meatBActionPerformed

    private void fishBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fishBActionPerformed
        try {
            String fish="fish";
            meth(fish);
        } catch (Exception ex) {
            Logger.getLogger(firstForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_fishBActionPerformed

    private void theListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_theListMouseClicked
        selected = theList.getSelectedValue();
        theList2.setModel(dm2);
        dm2.addElement(selected);
        
    }//GEN-LAST:event_theListMouseClicked

    private void removeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBActionPerformed
      // selected2 = theList2.getSelectedValue();
      // System.out.println(selected2);
       int selectedIndex = theList2.getSelectedIndex();
       if (selectedIndex != -1) {
            dm2.remove(selectedIndex);
        }
    }//GEN-LAST:event_removeBActionPerformed

    private void submitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBActionPerformed
        for(int i=0;i<theList2.getModel().getSize();i++){
            String x=theList2.getModel().getElementAt(i); 
            String[] splitStr = x.split("\\s+"); //xorizw to String mw vasi to keno
            //System.out.println(splitStr[0]);
            int idForInsert=Integer.parseInt((splitStr[0])); //downcast to id se int
            try {
                
                submit(idForInsert);
            } catch (Exception ex) {
                Logger.getLogger(firstForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        dm2.clear();
    }//GEN-LAST:event_submitBActionPerformed

    private void newOrderBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newOrderBActionPerformed
        try {
            newOrderF();
        } catch (SQLException ex) {
            Logger.getLogger(firstForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_newOrderBActionPerformed

    private void controlBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controlBActionPerformed
        setVisible(false);
        new SecondForm().setVisible(true);
    }//GEN-LAST:event_controlBActionPerformed

    private void queriesBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queriesBActionPerformed
        setVisible(false);
        try {
            new QueriesForm().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(firstForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_queriesBActionPerformed


    public static void main(String args[]) throws Exception {
        Class.forName(driverClassName);
        dbConnection=DriverManager.getConnection(url,username,password);
        dbConnection.close();
        

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new firstForm().setVisible(true);
            }
        });
    }
    public void meth(String nameOfTable)throws Exception{
        dm.clear();
        dbConnection=DriverManager.getConnection(url,username,password);
        statement=dbConnection.createStatement();
        
        ResultSet rs=statement.executeQuery("select * from "+nameOfTable);
        while (rs.next()) {
            theList.setModel(dm);
            String ID=rs.getString(1);
            String Name=rs.getString(2);
            String Timh=rs.getString(3);
            
           dm.addElement(ID+"   "+Name+"   "+Timh);

        }
        statement.close();
        dbConnection.close();
    }
    public void submit(int id)throws Exception{
        int quant=0; //dinoume 0 den mas noiazei giati tha ginei update
        dbConnection=DriverManager.getConnection(url,username,password);
        statement=dbConnection.createStatement();
        ResultSet rs=statement.executeQuery("select * from theorder where theid="+id);
        if(rs.next()){ //an uparxei to id idi tote to auksanw kata 1
            //statement.executeUpdate("update theorder set quantity=quantity+1 where theid="+id);
            try (Connection conn = this.connect();
            CallableStatement properCase = conn.prepareCall("{call updateTheOrder( ?,? ) }")) {
            properCase.setInt(1,id);
            properCase.setInt(2,quant);
            properCase.execute();
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
        }else{ //an den uparxei idi to id
            //statement.executeUpdate("insert into theorder (theid,quantity) values ("+id+",1)");
            try (Connection conn = this.connect();
            CallableStatement properCase = conn.prepareCall("{call addNewId( ?,? ) }")) {
            properCase.setInt(1,id);
            properCase.setInt(2, 1);
            properCase.execute();
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
        }
        statement.close();
        dbConnection.close();

    
    }
    public void newOrderF() throws SQLException{
        dbConnection=DriverManager.getConnection(url,username,password);
        statement=dbConnection.createStatement();
        
        ResultSet rs=statement.executeQuery("select * from orderno");
        while(rs.next()){
            numOfOrder=rs.getInt("arithmosparaggelias");
            viewName=Integer.toString(numOfOrder);
        }
        statement.executeUpdate("create view p"+viewName+" as select * from theorder"); //dimiourgia tou view
        statement.executeUpdate("update orderno set arithmosparaggelias=arithmosparaggelias+1"); //auksisi tou aritmou paraggelias
        statement.executeUpdate("delete from theorder"); //diagradh twn dedemenwn tou theorder wste na ksekinisei nea paraggelia
        statement.close();
        dbConnection.close();
        


    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appetizerB;
    private javax.swing.JButton beersB;
    private javax.swing.JButton controlB;
    private javax.swing.JButton fishB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton meatB;
    private javax.swing.JButton newOrderB;
    private javax.swing.JButton queriesB;
    private javax.swing.JButton removeB;
    private javax.swing.JButton saladsB;
    private javax.swing.JButton soft_drinksB;
    private javax.swing.JButton submitB;
    private javax.swing.JList<String> theList;
    private javax.swing.JList<String> theList2;
    // End of variables declaration//GEN-END:variables
}
